In [1]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np
arr = np.array(range(6))
print("Array:", arr)
print("Data type:", arr.dtype)

Array: [0 1 2 3 4 5]
Data type: int64


In [ ]:
#2. Given a NumPy array 'arr', check if its data type is float64.
#arr = np.array([1.5, 2.6, 3.7])
arr = np.array([1.5, 2.6, 3.7])
is_float = arr.dtype == np.float64
print("Is the data type float64?:", is_float)

Is the data type float64?: True


In [ ]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print("Array:", arr)
print("Data type:", arr.dtype)

Array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


In [ ]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(np.float32)
print("Original array:", arr)
print("Original data type:", arr.dtype)
print("Converted array:", arr_float)
print("Converted data type:", arr_float.dtype)

Original array: [1 2 3 4 5]
Original data type: int64
Converted array: [1. 2. 3. 4. 5.]
Converted data type: float32


In [ ]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1.123456789, 2.987654321, 3.141592653], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print("Original array:", arr)
print("Original data type:", arr.dtype)
print("Converted array:", arr_float32)
print("Converted data type:", arr_float32.dtype)

Original array: [1.12345679 2.98765432 3.14159265]
Original data type: float64
Converted array: [1.1234568 2.9876542 3.1415927]
Converted data type: float32


In [ ]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype

array = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(array)

print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)

Shape: (2, 3)
Size: 6
Data type: int64


In [ ]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(arr):
    return arr.ndim

array = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(array)

print("Dimensionality:", dimension)

Dimensionality: 2


In [ ]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size

array = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size_info(array)

print("Item size (in bytes):", item_size)
print("Total size (in bytes):", total_size)

Item size (in bytes): 8
Total size (in bytes): 48


In [ ]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    return arr.strides

array = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(array)

print("Strides:", strides)

Strides: (24, 8)


In [ ]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    return shape, strides

array = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(array)

print("Shape:", shape)
print("Strides:", strides)

Shape: (2, 3)
Strides: (24, 8)


In [ ]:
#11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
def create_zeros_array(n):
    return np.zeros(n)

n = 5
zeros_array = create_zeros_array(n)

print("Zeros array:", zeros_array)

Zeros array: [0. 0. 0. 0. 0.]


In [ ]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)

print("Ones matrix:")
print(ones_matrix)


Ones matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print("Range array:", range_array)

Range array: [0 2 4 6 8]


In [ ]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

start = 0.0
stop = 1.0
num = 5
linear_space = generate_linear_space(start, stop, num)
print("Linear space array:", linear_space)

Linear space array: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
    return np.eye(n)

n = 4
identity_matrix = create_identity_matrix(n)
print("Identity matrix:")
print(identity_matrix)

Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#16. Write a function that takes a Python list and converts it into a NumPy array.
def python_list_to_numpy_array(lst):
    return np.array(lst)

list1 = [1, 2, 3, 4, 5]
numpy_array = python_list_to_numpy_array(list1)
print("NumPy array:", numpy_array)

NumPy array: [1 2 3 4 5]


In [ ]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)
view_array = arr.view()
view_array[0] = 10
print("View of the array:", view_array)

Original array: [1 2 3 4 5]
View of the array: [10  2  3  4  5]


In [ ]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
result_axis_0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", result_axis_0)

result_axis_1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:\n", result_axis_1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_array = np.concatenate((arr1, arr2))
print("Concatenated array:", concatenated_array)

Concatenated array: [1 2 3 4 5 6]


In [ ]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertical_stack(arrays):
    return np.vstack(arrays)

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([7, 8, 9])
stacked_array = vertical_stack([array1, array2, array3])
print("Stacked array:\n", stacked_array)

Stacked array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def create_range_array(start, end, step=1):
    if start > end:
        raise ValueError("Start value cannot be greater than end value.")
    return np.arange(start, end + 1, step)
range_array = create_range_array(1, 10, 2)
print("Array of integers within the range:", range_array)


Array of integers within the range: [1 3 5 7 9]


In [ ]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def generate_linear_space(start, stop, num=10):
    return np.linspace(start, stop, num)

linear_space_array = generate_linear_space(0, 1)
print("Array of 10 equally spaced values:", linear_space_array)

Array of 10 equally spaced values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
def generate_log_space(start, stop, num=5):
    return np.logspace(start, stop, num)

log_space_array = generate_log_space(1, 1000, 5)
print("Array of 5 logarithmically spaced values:", log_space_array)

Array of 5 logarithmically spaced values: [1.00000000e+001 5.62341325e+250             inf             inf
             inf]


/usr/local/lib/python3.11/dist-packages/numpy/core/function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


In [ ]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import pandas as pd
import numpy as np

np.random.seed(42)
data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])
print(df)

   Column1  Column2  Column3
0       52       93       15
1       72       61       21
2       83       87       75
3       75       88      100
4       24        3       22


In [ ]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
def replace_negative_values(df, column_name):
    df[column_name] = df[column_name].apply(lambda x: 0 if x < 0 else x)
    return df

data = {'Column1': [1, -2, 3, -4, 5],
        'Column2': [6, -7, 8, -9, 10]}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

column_name = 'Column1'
df_replaced = replace_negative_values(df, column_name)
print(f"\nDataFrame after replacing negative values in '{column_name}':")
print(df_replaced)

Original DataFrame:
   Column1  Column2
0        1        6
1       -2       -7
2        3        8
3       -4       -9
4        5       10

DataFrame after replacing negative values in 'Column1':
   Column1  Column2
0        1        6
1        0       -7
2        3        8
3        0       -9
4        5       10


In [ ]:
#26. Access the 3rd element from the given NumPy array.
#arr = np.array([10, 20, 30, 40, 50])
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print("Third element:", third_element)

Third element: 30


In [ ]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
element = arr_2d[1, 2]
print("Element at (1, 2):", element)

Element at (1, 2): 6


In [ ]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
#arr = np.array([3, 8, 2, 10, 5, 7])
arr = np.array([3, 8, 2, 10, 5, 7])
greater_than_5 = arr[arr > 5]
print("Elements greater than 5:", greater_than_5)

Elements greater than 5: [ 8 10  7]


In [ ]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
#arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_array = arr[2:6]
print("Sliced array:", sliced_array)

Sliced array: [3 4 5 6]


In [ ]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array = arr_2d[:2, 1:]
print("Sub-array:\n", sub_array)

Sub-array:
 [[2 3]
 [5 6]]


In [ ]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
indices = np.array([[0, 1],
                   [1, 2]])
extracted_elements = arr_2d[indices[:, 0], indices[:, 1]]
print("Extracted elements:\n", extracted_elements)

Extracted elements:
 [2 6]


In [ ]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
arr = np.array([3, 8, 2, 10, 5, 7])
threshold = 5
filtered_array = arr[arr > threshold]
print("Filtered array:", filtered_array)

Filtered array: [ 8 10  7]


In [ ]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
def extract_elements_3d(array, x_indices, y_indices, z_indices):
    if array.ndim != 3:
        raise ValueError("Input array must be a 3D array.")
    if len(x_indices) != len(y_indices) or len(y_indices) != len(z_indices):
        raise ValueError("All index arrays must have the same length.")

    return array[x_indices, y_indices, z_indices]

array = np.arange(27).reshape(3, 3, 3)
x_indices = [0, 1, 2]
y_indices = [1, 2, 0]
z_indices = [2, 0, 1]

extracted_elements = extract_elements_3d(array, x_indices, y_indices, z_indices)
print("3D array:\n", array)
print("Extracted elements:", extracted_elements)


3D array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Extracted elements: [ 5 15 19]


In [ ]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
import numpy as np
def filter_elements_with_conditions(array, condition1, condition2):
    if array.ndim != 1:
        raise ValueError("Input array must be a 1D array.")
    if condition1.shape != condition2.shape:
        raise ValueError("Condition arrays must have the same shape.")
    return array[np.logical_and(condition1, condition2)]
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
condition1 = array > 3
condition2 = array % 2 == 0

result = filter_elements_with_conditions(array, condition1, condition2)
print("Original array:", array)
print("Filtered elements:", result)


Original array: [1 2 3 4 5 6 7 8 9]
Filtered elements: [4 6 8]


In [ ]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
import numpy as np

def extract_elements_2d(array, row_indices, col_indices):
    if len(row_indices) != len(col_indices):
        raise ValueError("Row and column indices must have the same length.")

    return array[row_indices, col_indices]

array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
row_indices = [0, 1, 2]
col_indices = [2, 1, 0]

extracted_elements = extract_elements_2d(array, row_indices, col_indices)
print("2D array:\n", array)
print("Extracted elements:", extracted_elements)


2D array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Extracted elements: [30 50 70]


In [ ]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = arr + 5

print("Original array:\n", arr)
print("Array after adding 5:\n", result)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after adding 5:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6, 7],
                 [8, 9, 10, 11],
                 [12, 13, 14, 15]])

result = arr1.T * arr2

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result after broadcasting:\n", result)


arr1:
 [[1 2 3]]
arr2:
 [[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Result after broadcasting:
 [[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


In [ ]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])
result = arr2 + arr1.T

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result after broadcasting:\n", result)


arr1:
 [[1 2 3 4]]
arr2:
 [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]
Result after broadcasting:
 [[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [ ]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
result = arr1 + arr2

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result after broadcasting:\n", result)

arr1:
 [[1]
 [2]
 [3]]
arr2:
 [[4 5 6]]
Result after broadcasting:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])
arr2_reshaped = arr2[:, :, np.newaxis]
result = arr1 * arr2_reshaped

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("arr2 reshaped:\n", arr2_reshaped)
print("Result of multiplication:\n", result)

arr1:
 [[1 2 3]
 [4 5 6]]
arr2:
 [[ 7  8]
 [ 9 10]]
arr2 reshaped:
 [[[ 7]
  [ 8]]

 [[ 9]
  [10]]]
Result of multiplication:
 [[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


In [ ]:
#41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_means = np.mean(arr, axis=0)

print("Original array:\n", arr)
print("Column-wise means:", column_means)

Original array:
 [[1 2 3]
 [4 5 6]]
Column-wise means: [2.5 3.5 4.5]


In [ ]:
#42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_values = np.max(arr, axis=1)

print("Original array:\n", arr)
print("Maximum values in each row:", max_values)

Original array:
 [[1 2 3]
 [4 5 6]]
Maximum values in each row: [3 6]


In [ ]:
#43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
indices = np.argmax(arr, axis=0)
print("Indices of maximum values in each column:", indices)

Indices of maximum values in each column: [1 1 1]


In [ ]:
#44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])
def moving_sum(arr, window_size=2):
    return np.apply_along_axis(lambda row: np.convolve(row, np.ones(window_size), mode='valid'), axis=1, arr=arr)
result = moving_sum(arr, window_size=2)

print("Original array:\n", arr)
print("Moving sum along rows:\n", result)


Original array:
 [[1 2 3]
 [4 5 6]]
Moving sum along rows:
 [[ 3.  5.]
 [ 9. 11.]]


In [ ]:
#45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
all_even = np.all(arr % 2 == 0, axis=0)

print("Original array:\n", arr)
print("All elements in each column are even:", all_even)

Original array:
 [[2 4 6]
 [3 5 7]]
All elements in each column are even: [False False False]


In [ ]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_matrix = original_array.reshape(2, 3)

print("Original array:\n", original_array)
print("Reshaped matrix:\n", reshaped_matrix)

Original array:
 [1 2 3 4 5 6]
Reshaped matrix:
 [[1 2 3]
 [4 5 6]]


In [ ]:
#47. Create a function that takes a matrix as input and returns the flattened array.
#input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
def flatten_matrix(matrix):
    return matrix.flatten()
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

flattened_array = flatten_matrix(input_matrix)

print("Input matrix:\n", input_matrix)
print("Flattened array:\n", flattened_array)

Input matrix:
 [[1 2 3]
 [4 5 6]]
Flattened array:
 [1 2 3 4 5 6]


In [ ]:
#48. Write a function that concatenates two given arrays along a specified axis.
#array1 = np.array([[1, 2], [3, 4]])
#array2 = np.array([[5, 6], [7, 8]])
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated_axis_0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", concatenated_axis_0)

concatenated_axis_1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:\n", concatenated_axis_1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis.
#original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def split_array(arr, num_splits, axis=0):
    return np.split(arr, num_splits, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
splits_axis_0 = split_array(original_array, num_splits=3, axis=0)
print("Split along axis 0 (rows):")
for sub_array in splits_axis_0:
    print(sub_array)

splits_axis_1 = split_array(original_array, num_splits=3, axis=1)
print("\nSplit along axis 1 (columns):")
for sub_array in splits_axis_1:
    print(sub_array)


Split along axis 0 (rows):
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Split along axis 1 (columns):
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [ ]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
#original_array = np.array([1, 2, 3, 4, 5])
#indices_to_insert = [2, 4]
#values_to_insert = [10, 11]
#indices_to_delete = [1, 3]
def modify_array(arr, indices_to_insert, values_to_insert, indices_to_delete):
    arr_after_insert = np.insert(arr, indices_to_insert, values_to_insert)
    arr_after_delete = np.delete(arr_after_insert, indices_to_delete)

    return arr_after_insert, arr_after_delete

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

arr_after_insert, arr_after_delete = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Original array:", original_array)
print("Array after insertion:", arr_after_insert)
print("Array after deletion:", arr_after_delete)


Original array: [1 2 3 4 5]
Array after insertion: [ 1  2 10  3  4 11  5]
Array after deletion: [ 1 10  4 11  5]


In [ ]:
#51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.
arr1 = np.random.randint(1, 11, size=5)
arr2 = np.arange(1, 6)
result = arr1 + arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise addition:", result)


arr1: [5 2 8 6 2]
arr2: [1 2 3 4 5]
Result of element-wise addition: [ 6  4 11 10  7]


In [ ]:
#52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise subtraction:", result)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result of element-wise subtraction: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [ ]:
#53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.
arr1 = np.random.randint(1, 11, size=5)
arr2 = np.arange(1, 6)
result = arr1 * arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise multiplication:", result)


arr1: [ 5  1 10  6  9]
arr2: [1 2 3 4 5]
Result of element-wise multiplication: [ 5  2 30 24 45]


In [ ]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
result = arr1 / arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise division:", result)


arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Result of element-wise division: [2. 2. 2. 2. 2.]


In [ ]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
result = arr1 ** arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise exponentiation:", result)

arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Result of element-wise exponentiation: [ 1 16 27 16  5]


In [ ]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
#arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
def count_substring_occurrences(arr, substring):
    occurrences = np.char.count(arr, substring)
    return occurrences.sum()
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

count = count_substring_occurrences(arr, substring)
print(f"The substring '{substring}' appears {count} times in the array.")

The substring 'hello' appears 3 times in the array.


In [ ]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.
#arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
def extract_uppercase(arr):
    uppercase_chars = np.char.array(arr)
    result = np.array([''.join([ch for ch in string if ch.isupper()]) for string in uppercase_chars])

    return result
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase(arr)
print("Extracted uppercase characters:", uppercase_chars)

Extracted uppercase characters: ['H' 'W' 'OAI' 'GPT']


In [ ]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def replace_substring(arr, old_substring, new_substring):
    result = np.char.replace(arr, old_substring, new_substring)
    return result
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'fruit'

updated_arr = replace_substring(arr, old_substring, new_substring)
print("Updated array:", updated_arr)


Updated array: ['fruit' 'banana' 'grape' 'pinefruit']


In [ ]:
#59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
def concatenate_strings(arr1, arr2):
    result = np.char.add(arr1, arr2)
    return result
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

concatenated_arr = concatenate_strings(arr1, arr2)
print("Concatenated array:", concatenated_arr)


Concatenated array: ['HelloOpen' 'WorldAI']


In [ ]:
#60. Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def longest_string_length(arr):
    lengths = np.vectorize(len)(arr)
    return np.max(lengths)
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_length = longest_string_length(arr)
print("Length of the longest string:", longest_length)


Length of the longest string: 9


In [ ]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)
print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)


Dataset: [528 617 412 376  52 416 961 941 666  90 575 982 295  82 561 717 758 954
 569 698 166 367 276 842 211 964 163 527 941 735 600 944 743 886 347 444
 879 590 487 359 466 625 923 154  33 590 271 157 849 555 568 912 317 136
 694 932 124 273 907 795 655 902 620  43  97 987 980 575 255 505 599 192
 787 527 101 907 696 709  76 395 781 550 207  47 820 581 213 326 655 885
 181 131 484 831 778 979  98 963 648 444]
Mean: 542.12
Median: 572.0
Variance: 86240.9456
Standard Deviation: 293.6680874729156


In [ ]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
dataset = np.random.uniform(1, 100, size=50)

percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)
print("Dataset:", dataset)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Dataset: [83.76591751  7.99260108 52.96394048 70.81530598 24.07334495 13.18702356
 36.1897398  88.37733731  8.72356554 81.91252199 37.57786496 32.8626967
 95.66324769 18.04203073  9.99986072 25.60251563 77.52683148 45.95492535
 83.88537023 70.82036552 71.29348393 36.0107958  47.05312812 32.2953503
 91.57801321 56.00810508 34.03916791  6.10916409 87.63680219 55.29961296
 59.66673569 99.73529579 22.23836532 88.89394496 19.83654819 20.81550836
 94.205262   60.98311949 13.98717676 33.05145107 27.42351214 64.24586422
 21.19563371 32.68998912 77.70557226 37.2409225  15.86459051  4.18081666
 25.41614723 30.47836922]
25th Percentile: 22.697110229194386
75th Percentile: 71.17520432560651


In [ ]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

array1 = np.random.randint(1, 101, size=10)
array2 = np.random.randint(1, 101, size=10)
correlation_matrix = np.corrcoef(array1, array2)
correlation_coefficient = correlation_matrix[0, 1]

print("Array 1:", array1)
print("Array 2:", array2)
print("Correlation Matrix:\n", correlation_matrix)
print("Correlation Coefficient:", correlation_coefficient)


Array 1: [ 3 29 54 81 33 37 74 27 46 78]
Array 2: [78 79 96 16 23  6 71 92 95 95]
Correlation Matrix:
 [[ 1.         -0.06967689]
 [-0.06967689  1.        ]]
Correlation Coefficient: -0.06967688748153507


In [ ]:
#64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])
result = np.dot(matrix1, matrix2)
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Result of Matrix Multiplication:\n", result)


Matrix 1:
 [[1 2 3]
 [4 5 6]]
Matrix 2:
 [[ 7  8]
 [ 9 10]
 [11 12]]
Result of Matrix Multiplication:
 [[ 58  64]
 [139 154]]


In [ ]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
array = np.random.randint(10, 1001, size=50)

percentile_10 = np.percentile(array, 10)
percentile_50 = np.percentile(array, 50)
percentile_90 = np.percentile(array, 90)

first_quartile = np.percentile(array, 25)
third_quartile = np.percentile(array, 75)
print("Array:", array)
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", first_quartile)
print("Third Quartile (75th Percentile):", third_quartile)


Array: [685 450 494 931 950 680 912 993 175  63 382 963 222 695 950 761  44 174
 903 581 177 591 132 493 829 388 860  96 410 137 391 238 640  73 457 494
 419 725 833 513 901 257 166 470 638 192 622 337 858 486]
10th Percentile: 136.5
50th Percentile (Median): 493.5
90th Percentile: 913.9
First Quartile (25th Percentile): 242.75
Third Quartile (75th Percentile): 752.0


In [ ]:
#66. Create a NumPy array of integers and find the index of a specific element.
array = np.array([10, 20, 30, 40, 50, 60, 70, 80])
element_to_find = 40
index = np.where(array == element_to_find)[0]
print("Array:", array)
print(f"Index of element {element_to_find}:", index)


Array: [10 20 30 40 50 60 70 80]
Index of element 40: [3]


In [ ]:
#67. Generate a random NumPy array and sort it in ascending order.
random_array = np.random.randint(1, 101, size=10)
sorted_array = np.sort(random_array)
print("Original Array:", random_array)
print("Sorted Array (Ascending):", sorted_array)

Original Array: [98 32 12 81 26 70  8 29 99 73]
Sorted Array (Ascending): [ 8 12 26 29 32 70 73 81 98 99]


In [ ]:
#68. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])
filtered_arr = arr[arr > 20]
print("Filtered Array (elements > 20):", filtered_arr)


Filtered Array (elements > 20): [25 42 30]


In [ ]:
#69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
filtered_arr = arr[arr % 3 == 0]
print("Filtered Array (elements divisible by 3):", filtered_arr)


Filtered Array (elements divisible by 3): [12 15]


In [ ]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr >= 20) & (arr <= 40)]
print("Filtered Array (elements ≥ 20 and ≤ 40):", filtered_arr)


Filtered Array (elements ≥ 20 and ≤ 40): [20 30 40]


In [ ]:
#71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print("Byte order of the array:", byte_order)

Byte order of the array: =


In [2]:
#72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print("Array after byte swapping:", arr)

Array after byte swapping: [16777216 33554432 50331648]


In [4]:
#73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.newbyteorder()
print("Original array:", arr)
print("Swapped Array:", swapped_arr)

Original array: [1 2 3]
Swapped Array: [16777216 33554432 50331648]


In [7]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':
    print("System's byte order is native. Conditionally swapping...")
    swapped_arr = arr.newbyteorder()
else:
    print("System's byte order is already specified (big or little). No swap needed.")
    swapped_arr = arr

print("Original array:", arr)
print("Array after conditional byte order swap:", swapped_arr)


System's byte order is native. Conditionally swapping...
Original array: [1 2 3]
Array after conditional byte order swap: [16777216 33554432 50331648]


In [8]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':
    print("No byte swapping is necessary. The array already uses the system's native byte order.")
elif arr.dtype.byteorder == '<':
    print("The array is in little-endian format.")
elif arr.dtype.byteorder == '>':
    print("The array is in big-endian format.")
else:
    print("Unknown byte order.")

print("Array byte order:", arr.dtype.byteorder)


No byte swapping is necessary. The array already uses the system's native byte order.
Array byte order: =


In [9]:
#76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 99
print("Original array (arr1):", arr1)
print("Modified copy (copy_arr):", copy_arr)
if np.array_equal(arr1, copy_arr):
    print("Modifying copy_arr affected arr1.")
else:
    print("Modifying copy_arr does NOT affect arr1.")


Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified copy (copy_arr): [99  2  3  4  5  6  7  8  9 10]
Modifying copy_arr does NOT affect arr1.


In [10]:
#77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
matrix = np.random.randint(1, 10, size=(3, 3))
view_slice = matrix[1:, 1:]
view_slice[0, 0] = 99
print("Original matrix after modification:")
print(matrix)
print("\nSlice (view_slice) after modification:")
print(view_slice)
if matrix[1, 1] == view_slice[0, 0]:
    print("\nModifying view_slice affects the original matrix.")
else:
    print("\nModifying view_slice does NOT affect the original matrix.")


Original matrix after modification:
[[ 6  8  5]
 [ 6 99  1]
 [ 7  8  2]]

Slice (view_slice) after modification:
[[99  1]
 [ 8  2]]

Modifying view_slice affects the original matrix.


In [11]:
#78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :]
view_b += 5
print("Original array (array_a) after broadcasting addition:")
print(array_a)
print("\nSlice (view_b) after broadcasting addition:")
print(view_b)
if np.any(array_a[:2, :] == view_b):
    print("\nBroadcasting addition to view_b alters the original array.")
else:
    print("\nBroadcasting addition to view_b does NOT alter the original array.")


Original array (array_a) after broadcasting addition:
[[ 6  7  8]
 [ 9 10 11]
 [ 7  8  9]
 [10 11 12]]

Slice (view_b) after broadcasting addition:
[[ 6  7  8]
 [ 9 10 11]]

Broadcasting addition to view_b alters the original array.


In [12]:
#79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[1, 0] = 99
print("Original array (orig_array) after modification:")
print(orig_array)
print("\nReshaped view (reshaped_view) after modification:")
print(reshaped_view)
if np.any(orig_array == 99):
    print("\nModifying reshaped_view reflects changes in orig_array.")
else:
    print("\nModifying reshaped_view does NOT reflect changes in orig_array.")


Original array (orig_array) after modification:
[[ 1  2 99  4]
 [ 5  6  7  8]]

Reshaped view (reshaped_view) after modification:
[[ 1  2]
 [99  4]
 [ 5  6]
 [ 7  8]]

Modifying reshaped_view reflects changes in orig_array.


In [13]:
#80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
data = np.random.randint(1, 11, size=(3, 4))
data_copy = data[data > 5].copy()
if len(data_copy) > 0:
    data_copy[0] = 99
print("Original array (data):")
print(data)
print("\nModified copy (data_copy):")
print(data_copy)
if 99 in data:
    print("\nModifying data_copy affects the original array.")
else:
    print("\nModifying data_copy does NOT affect the original array.")


Original array (data):
[[ 7  6  5  5]
 [10  6  2  6]
 [ 4  8  3  2]]

Modified copy (data_copy):
[99  6 10  6  6  8]

Modifying data_copy does NOT affect the original array.


In [14]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
addition_result = A + B
subtraction_result = A - B
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition of A and B:")
print(addition_result)
print("\nSubtraction of A and B:")
print(subtraction_result)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition of A and B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction of A and B:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [15]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
C = np.random.randint(1, 10, (3, 2))
D = np.random.randint(1, 10, (2, 4))
result = np.dot(C, D)
print("Matrix C (3x2):")
print(C)
print("\nMatrix D (2x4):")
print(D)
print("\nResult of matrix multiplication (3x4):")
print(result)

Matrix C (3x2):
[[1 2]
 [4 8]
 [3 8]]

Matrix D (2x4):
[[4 8 3 7]
 [3 3 8 1]]

Result of matrix multiplication (3x4):
[[10 14 19  9]
 [40 56 76 36]
 [36 48 73 29]]


In [16]:
#83. Create a matrix `E` and find its transpose.
E = np.random.randint(1, 10, (3, 2))
E_transpose = E.T
print("Matrix E (3x2):")
print(E)
print("\nTranspose of Matrix E (2x3):")
print(E_transpose)

Matrix E (3x2):
[[8 9]
 [4 7]
 [5 5]]

Transpose of Matrix E (2x3):
[[8 4 5]
 [9 7 5]]


In [17]:
#84. Generate a square matrix `F` and compute its determinant.
F = np.random.randint(1, 10, (3, 3))
determinant = np.linalg.det(F)
print("Matrix F (3x3):")
print(F)
print("\nDeterminant of Matrix F:")
print(determinant)

Matrix F (3x3):
[[5 7 8]
 [8 8 9]
 [3 8 4]]

Determinant of Matrix F:
84.99999999999994


In [18]:
#85. Create a square matrix `G` and find its inverse
G = np.random.randint(1, 10, (3, 3))
if np.linalg.det(G) != 0:
    inverse_G = np.linalg.inv(G)
    print("Matrix G (3x3):")
    print(G)
    print("\nInverse of Matrix G:")
    print(inverse_G)
else:
    print("Matrix G is singular and does not have an inverse.")

Matrix G (3x3):
[[4 9 6]
 [1 3 2]
 [2 5 9]]

Inverse of Matrix G:
[[ 1.         -3.          0.        ]
 [-0.29411765  1.41176471 -0.11764706]
 [-0.05882353 -0.11764706  0.17647059]]
